version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pytest --cov=termatopy tests/
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            codecov --token=$CODECOV_TOKEN
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            - "dist"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
